# -*- coding: utf-8 -*-
"""webcrawler_fmi.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VMt9zlP2AZHAGbPfmNMUhl2hFslI9jJq
"""

# importar bibliotecas
import requests
from bs4 import BeautifulSoup

# definir url de pesquisa
url = 'https://www.imf.org/external/country/BRA/index.htm'

# realizar os requests
page = requests.get(url)

# transformar a resposta em um objeto BeautifulSoup
soup = BeautifulSoup(page.text, 'html.parser')

# selecionar os dados desejados
dados = soup.find_all('div', {'class': 'm-table-data'})

# criar um dicionário para armazenar os dados
dados_fmi = {}

# percorrer os dados e armazenar no dicionário
for dado in dados:
    nome = dado.find('div', {'class': 'm-table-data-title'}).text
    valor = dado.find('div', {'class': 'm-table-data-value'}).text

# imprimir os dados
print('Estes dados são do FMI:', dados_fmi)